---
version: 2.1
orbs:
  cloudsmith: cloudsmith/cloudsmith@1.0.4
executors:
  boot-linux:
    machine:
      enabled: true
      image: ubuntu-2004:202010-01
commands:
  git-checkout:
    steps:
      - run: git clone -b "debian/2.40.0+dfsg-5" https://salsa.debian.org/gnome-team/gdk-pixbuf.git .
      - run: wget -nc -O - https://github.com/bareboat-necessities/gdk-pixbuf/archive/master.tar.gz | gzip -cd - | tar xvf - ; mv *-master/.circleci .
  build-n-publish-debian:
    steps:
      - run: sudo apt-get -y install debhelper
      - run: chmod a+x .circleci/*.sh
      - run:
          command: |
            .circleci/build-debian.sh
          no_output_timeout: 30m
      - cloudsmith/ensure-api-key
      - cloudsmith/install-cli
      - run: .circleci/publish-cloudsmith.sh deb bbn-projects/bbn-repo ${PKG_DISTRO}
jobs:
  build-debian-buster-arm64:
    executor: boot-linux
    environment:
      - DOCKER_IMAGE=arm64v8/debian:buster
      - CONTAINER_DISTRO=debian:buster
      - PKG_DISTRO=debian/buster
      - EMU=on
    steps:
      - git-checkout
      - build-n-publish-debian
  build-raspbian-buster-arm32:
    executor: boot-linux
    environment:
      - DOCKER_IMAGE=jongough/raspbian-buster:plugin_build_tooling_current
      - CONTAINER_DISTRO=raspbian
      - PKG_DISTRO=raspbian/buster
      - EMU=on
    steps:
      - git-checkout
      - build-n-publish-debian
  build-debian-buster-amd64:
    executor: boot-linux
    environment:
      - DOCKER_IMAGE=amd64/debian:buster
      - CONTAINER_DISTRO=debian:buster
      - PKG_DISTRO=debian/buster
    steps:
      - git-checkout
      - build-n-publish-debian
workflows:
  version: 2
  build_all:
    jobs:
      - build-debian-buster-arm64
      - build-raspbian-buster-arm32
      - build-debian-buster-amd64
